/**
 * @file bhs.h
 * @brief Branding Image Resource
 * 
 * Contains the compiled image resource for BHS logo.
 * Optimized for embedded displays with:
 * - ROM storage (no dynamic allocation)
 * - LVGL compatibility
 * - Color depth matching target display
 *
 * @note Image is stored in PROGMEM (ESP32 flash)
 * @version 1.0
 * @date 2025-06-01
 */

#ifndef BHS_H
#define BHS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/**
 * @brief BHS logo image descriptor.
 *
 * LVGL-compatible image descriptor for the BHS logo. This resource is stored in PROGMEM for efficient flash usage on ESP32.
 *
 * @note Do not modify - generated by image converter.
 * @note Use with LVGL image widgets for branding display.
 */
extern const lv_img_dsc_t BHS;

#ifdef __cplusplus
}
#endif

#endif /* BHS_H */
